version: '3.8'

services:

  mysql_server:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MYSQL_DATABASE=fullstack_shop
    ports:
      - '3306:3306'
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    depends_on:
      - mysql_server