version: '3.8'

services:

  mysql_server:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=process.env.MYSQL_DATABASE
      - MYSQL_USER=process.env.MYSQL_USER
      - MYSQL_PASSWORD=process.env.MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=process.env.MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    depends_on:
      - mysql_server